# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 别院牧志
subtitle: IMOYAO
description: 深深别院，潜潜牧志。一个独立博客，使用 Python 语言开发，专注于云计算方向。致力于写出 Pythonic 的代码。
author: imoyao
email: immoyao@gmail.com
slogan: 就命运而言，休论公道。
keywords: 别院牧志, imoyao, idealyard, 张牧志, 牧志, Python, 编程, Python开发
#language: zh-Hans    # for next
language: zh-CN       # for material
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.masantu.com/
root: /
#permalink: :year/:month/:day/:title/
permalink: blog/:year-:month-:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site
  exclude: ['www.masantu.com','blog.masantu.com','masantu.com']
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

auto_dir_categorize:
	enable: true  # options:true, false; default is true
	force: false # options:true, false; default is false
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#主题更改
#theme: next
#theme: material
#theme: inside
#theme: idealyard
#theme: cactus
theme: Butterfly

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: https://github.com/imoyao/imoyao.github.io.git
    gitee: https://gitee.com/imoyao/imoyao.git
  #  repo: git@github.com:imoyao/imoyao.github.io.git

  branch: master
# Local Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 代码高亮方案https://github.com/ele828/hexo-prism-plugin
#prism_plugin:
#  mode: 'preprocess'    # realtime/preprocess
#  theme: 'hopscotch'
#  line_number: true    # default false

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# 链接添加 nofollow，https://github.com/hexojs/hexo-filter-nofollow
nofollow:
  enable: true
  field: site
  exclude:
    - 'www.masantu.com'
    - 'blog.masantu.com'
    - 'masantu.com'

sitemap:
  path: sitemap.xml

# https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 2
  wpm: 300

netlify_cms:
  config_file: netlify-cms.yaml

douban:
  user: imoyao
  builtin: false
  book:
    title: '阅读，与另一个灵魂进行对话'
    quote: '楼下一个男人病得要死，那间隔壁的一家唱着留声机，对面是弄孩子。楼上有两人狂笑，还有打牌声。河中的船上有女人哭着她死去的母亲。人类的悲欢并不相通，我只觉得他们吵闹。<div align = right> ——鲁迅·《而已集·小杂感》 </div>'
  movie:
    title: '电影，探索生活在别处的可能'
    quote: '你只是个孩子，你根本不晓得你在说什么。<br>
所以问你艺术,你可能会提出艺术书籍中的粗浅论调。有关米开朗基罗，你知道很多，他的满腔政治热情，与教皇相交莫逆，耽于性爱，你对他很清楚吧？但你连西斯汀教堂的气味也不知道吧？你没试过站在那儿，昂首眺望天花板上的名画吧？肯定未见过吧？<br>
如果我问关于女人的事，你大可以向我如数家珍，你可能上过几次床，但你没法说出在女人身旁醒来时，那份内心真正的喜悦。<br>
你年轻彪悍，我如果和你谈论战争，你会向我大抛莎士比亚，朗诵“共赴战场，亲爱的朋友”，但你从未亲临战阵，未试过把挚友的头拥入怀里，看着他吸着最后一口气，凝望着你，向你求助。<br>
我问你何为爱情，你可能只会吟风弄月，给我背十四行诗，但你未试过全情投入真心倾倒，四目交投时彼此了解对方的心，好比上帝安排天使下凡只献给你，把你从地狱深渊拯救出来，对她百般关怀的感受你也从未试过，你从未试过对她的情深款款矢志厮守，明知她患了绝症也在所不惜，你从未尝试过痛失挚爱的感受……<div align = right> ——《心灵捕手》</div>'
#  game:
#    title: 'This is my game title'
#    quote: 'This is my game quote'
  timeout: 20000
# https://github.com/printempw/hexo-hide-posts
# hexo-hide-posts
hide_posts:
  # Change the filter name to fit your need
  filter: hide
  # Generators which you want to expose all posts (include hidden ones) to.
  # Common generators: index, tag, category, archive, sitemap, feed, etc.
  public_generators: []
  # Add "noindex" meta tag to prevent hidden posts from being indexed by search engines
  noindex: true