categories: Categories
search: Search
tags: Tags
tagcloud: "Tag Cloud"
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: "Page %d"
recent_posts: "Recent Posts"
description: Description
read_more: "Read More"
links: Links
top: Pin
no_comment: "No comments yet. Press the button and go to comment now!"
go_to_comment: "Go to comment"
recent_comments: "Recent Comments"
recommended_posts: "Recommended Posts"
