# Menus
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags

back_home: https://masantu.com/

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: /img/vertical-logo.png
    profile:
        enabled: false # Whether to show profile bar
        avatar: # css/images/avatar.png
        gravatar: zth_9451@qq.com # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: imoyao
        author_title: Devoloper
        location: Beijing, China
        follow: https://github.com/imoyao/
    highlight: monokai
    sidebar: left # sidebar position, options: left, right
    category_perExpand: false # enable article categories list per expanding
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: /img/favicon.ico # path to favicon
    default_index_file: index.md # if this, it will display at site index instead of default index page
    social_links:
        github: https://github.com/imoyao
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets: # default use category only
    - category
    # - recent_posts
    # - archive
    # - tag
    # - tagcloud
    # - links
    
# Excerpt 
## Auto creat excerpt with not <!--more-->
## Enable will truncate auto_excerpt.lines rows in post head to replace excerpt.
auto_excerpt:
    enable: true
    lines: 5

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# History version
# https://github.com/imoyao/imoyao.github.io/edit/hexo/blog/wiki/_posts/index.md
# https://github.com/imoyao/imoyao.github.io/raw/hexo/blog/wiki/_posts/index.md
history_control: # make you wiki has history version control in page
    enable: true
    server_link: https://github.com # recommend use GitHub https://github.com
    user: imoyao
    repertory: imoyao.github.io
    branch: hexo
    subdir: blog
    wiki_source: wiki


# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    mathjax: true # options: true, false - to enable use Mathjax in your article
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key
    busuanzi_count: true # options: true, false - to enable busuanzi site pv statistics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:

# Note (Bootstrap Callout)
# https://muse.theme-next.org/docs/tag-plugins/note
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0